<?php

declare(strict_types=1);

return [
    'visible_prefixes' => [
        '.github/workflows',
        'private/docs',
        'private/docs/calendar',
        'private/framework/',
        'private/framework/calendar',
        'private/framework/contracts',
        'private/framework/dreams',
        'private/framework/entity',
        'private/framework/entities',
        'private/framework/expression',
        'private/framework/prose',
        'private/framework/support',
        'public_html/pecherie/chill-api/',
        'public_html/pecherie/chill-api/repo',
        'public_html/pecherie/chill-api/choreography',
        'public_html/pecherie/chill-api/entity',
        'public_html/pecherie/chill-api/expression',
        'public_html/pecherie/chill-api/audit',
        'public_html/pecherie/chill-api/calendar',
        'public_html/pecherie/chill-api/prose',
        'public_html/pecherie/chill-api/reference',
        'public_html/pecherie/chill-api/music',
        'public_html/pecherie/chill-api/dreams',
        'public_html/pecherie/chill-api/limbic',
    ],

    'visible_files' => [
        'private/framework/procedures/procedure_registry_reader.php',
        'private/framework/procedures/procedure_source_inspector.php',
        'private/framework/procedures/calendar_event_id.php',
        'private/framework/calendar/calendar_event_projection_target_guard.php',
        'private/framework/calendar/calendar_hierarchy_validator.php',
        'private/framework/calendar/calendar_node_ensurer.php',
        'private/framework/directives/directive_text.php',
        'private/framework/directives/directive_validator.php',
        'public_html/pecherie/chill-api/index.php',
        'public_html/pecherie/chill-api/query.php',
        'public_html/pecherie/chill-api/tables.php',
        'public_html/pecherie/chill-api/columns.php',
    ],

    'required_operations' => [
        'listRepo' => 'public_html/pecherie/chill-api/repo/list_repo.php',
        'getRepoFile' => 'public_html/pecherie/chill-api/repo/get_repo_file.php',
        'executeSqlRead' => 'public_html/pecherie/chill-api/query.php',
        'tables' => 'public_html/pecherie/chill-api/tables.php',
        'columns' => 'public_html/pecherie/chill-api/columns.php',
        'query' => 'public_html/pecherie/chill-api/query.php',
        'resolveMedleyCore' => 'public_html/pecherie/chill-api/choreography/resolve_medley_core.php',
        'runChoreography' => 'public_html/pecherie/chill-api/choreography/run_choreography.php',
        'suggestLinkEntity' => 'public_html/pecherie/chill-api/entity/suggest_link_entity.php',
        'auditTraversalTriggerIntegrity' => 'public_html/pecherie/chill-api/audit/traversal_trigger_integrity.php',
        'auditEventGraphIdentity' => 'public_html/pecherie/chill-api/audit/event_graph_identity.php',
        'resolveEntityTraversal' => 'public_html/pecherie/chill-api/entity/resolve_entity_traversal.php',
        'resolveEntityMeasurements' => 'public_html/pecherie/chill-api/entity/resolve_entity_measurements.php',
        'resolveCharacterExpressionOutput' => 'public_html/pecherie/chill-api/expression/resolve_character_expression_output.php',
        'createCalendarWeek' => 'public_html/pecherie/chill-api/calendar/create_calendar_week.php',
        'createCalendarDay' => 'public_html/pecherie/chill-api/calendar/create_calendar_day.php',
        'createCalendarTime' => 'public_html/pecherie/chill-api/calendar/create_calendar_time.php',
        'createCalendarEvent' => 'public_html/pecherie/chill-api/calendar/create_calendar_event.php',
        'createCalendarSubevent' => 'public_html/pecherie/chill-api/calendar/create_calendar_subevent.php',
        'getCalendarNodeByChronologyAddress' => 'public_html/pecherie/chill-api/calendar/get_calendar_node_by_chronology_address.php',
        'listYears' => 'public_html/pecherie/chill-api/reference/list_years.php',
        'listChoreographyTypes' => 'public_html/pecherie/chill-api/reference/list_choreography_types.php',
        'listRoutineStatuses' => 'public_html/pecherie/chill-api/reference/list_routine_statuses.php',
        'executeEntityTraversal' => 'public_html/pecherie/chill-api/entity/execute_entity_traversal.php',
        'auditTraversalStepChainIntegrity' => 'public_html/pecherie/chill-api/audit/traversal_step_chain_integrity.php',
        'auditTraversalProjectionIntegrity' => 'public_html/pecherie/chill-api/audit/traversal_projection_integrity.php',
        'auditTraversalJoinSemantics' => 'public_html/pecherie/chill-api/audit/traversal_join_semantics.php',
        'auditTraversalOptionalityIntegrity' => 'public_html/pecherie/chill-api/audit/traversal_optionality_integrity.php',
        'listTeamRoles' => 'public_html/pecherie/chill-api/reference/list_team_roles.php',
        'resolveSongArtistPair' => 'public_html/pecherie/chill-api/music/resolve_song_artist_pair.php',
        'runExpressionPipeline' => 'public_html/pecherie/chill-api/expression/run_expression_pipeline.php',
        'suggestEntityEventThemeLink' => 'public_html/pecherie/chill-api/expression/suggest_entity_event_theme_link.php',
        'applyEntityEventThemeLink' => 'public_html/pecherie/chill-api/expression/apply_entity_event_theme_link.php',
        'applyLimbicFact' => 'public_html/pecherie/chill-api/limbic/apply_limbic_fact.php',
        'resolveProseCalendarTarget' => 'public_html/pecherie/chill-api/prose/resolve_prose_calendar_target.php',
        'createProseDraft' => 'public_html/pecherie/chill-api/prose/create_prose_draft.php',
        'addProseAnnotations' => 'public_html/pecherie/chill-api/prose/add_prose_annotations.php',
        'getProseAnnotations' => 'public_html/pecherie/chill-api/prose/get_prose_annotations.php',
        'getProseTrainingView' => 'public_html/pecherie/chill-api/prose/get_prose_training_view.php',
        'createDreamJournalEntry' => 'public_html/pecherie/chill-api/dreams/create_dream_journal_entry.php',
        'getDreamJournalEntries' => 'public_html/pecherie/chill-api/dreams/get_dream_journal_entries.php',
        'getDreamAnnotations' => 'public_html/pecherie/chill-api/dreams/get_dream_annotations.php',
        'getCalendarTreeForEntity' => 'public_html/pecherie/chill-api/calendar/get_calendar_tree_for_entity.php',
        'generateCalendarBatchFromProse' => 'public_html/pecherie/chill-api/calendar/generate_calendar_batch_from_prose.php',
        'executeCalendarBatchFromProse' => 'public_html/pecherie/chill-api/calendar/execute_calendar_batch_from_prose.php',
        'resolveProseExportText' => 'public_html/pecherie/chill-api/prose/resolve_prose_export_text.php',
    ],
];